#!/bin/sh

set -e

lb config noauto \
     --apt-recommends 'false' \
     --apt-source-archives 'false' \
     --apt-indices 'false' \
     --archive-areas "main contrib non-free non-free-firmware" \
     --debian-installer 'live' \
     --debian-installer-distribution 'trixie' \
     --distribution 'trixie' \
     --bootappend-live 'boot=live components hostname=waydog user-default-groups=audio,cdrom,dip,floppy,video,input,plugdev,netdev,powerdev,scanner,bluetooth,fuse,systemd-journal quiet splash' \
     --mirror-binary 'https://deb.debian.org/debian' \
     --mirror-binary-security 'https://security.debian.org/debian-security' \
     --mirror-bootstrap 'https://deb.debian.org/debian' \
     --firmware-binary 'true' \
     --firmware-chroot 'true' \
     --security 'true' \
     --memtest 'memtest86+' \
     --image-name 'Waydog-Trixie-26.09.03' \
     --iso-application 'Waydog-Trixie' \
     --iso-publisher 'Waydog-Trixie GNU/Linux' \
     --iso-volume 'Waydog-Trixie' \
     --system 'live' \
     --updates 'true' \
     --win32-loader 'false' \
     --zsync 'false' \
     --quiet \
     "${@}"
